{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiplan-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{.Values.ingress.host}}
    secretName: {{.Values.ingress.tls.secretName}}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: aiplan
              port:
                number: 8080
        - path: /uploads/
          pathType: Prefix
          backend:
            service:
              name: minio
              port:
                number: 9000
{{- if .Values.ingress.tls.issuer }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-cluster
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.Values.ingress.tls.issuer}}
    privateKeySecretRef:
      name: letsencrypt-cluster
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Values.ingress.tls.secretName}}-cert
spec:
  secretName: {{.Values.ingress.tls.secretName}}
  issuerRef:
    name: letsencrypt-cluster
  commonName: {{.Values.ingress.host}}
  dnsNames:
  - {{.Values.ingress.hopst}}
{{- end }}
{{- end }}
